NCIOCPL/clinical-trials-listing-app

.pa11yci, cypress/integration/AppAnalytics/DiseaseAnalytics.feature, cypress/integration/DiseaseCode.feature, cypress/integration/DiseaseCodeUglyToPrettyURL.feature, cypress/integration/common/index.js, src/views/CTLViewsHoC.jsx, src/views/__tests__/CTLViewsHoC.PrettyURLRedirect.test.js, src/views/__tests__/CTLViewsHoC.test.js
Closes #14
* Added feature file for integration test
=> (#14) Redirect Ugly Urls to Pretty Urls for Disease

support/mock-data/listing-information/c123455-404.json, support/mock-data/listing-information/chicken-nuggets-404.json
Closes #45
* Update mock data to have correct Listing API error message response
=> (#45) Update API error message

src/views/Disease/Disease.jsx, src/views/Manual/Manual.jsx
- removed the condition of having query response
loading finished before displaying intro text
Close #49
=> (#49) fixed the condition for intro text display

src/index.js
Closes #56
* Update initialize function name to ClinicalTrialsListingApp
=> (#56) Update initialize function name

cypress/integration/AppAnalytics/AdultMetastaticBrainTumorAnalytics.feature, cypress/integration/common/index.js, src/components/molecules/results-list/__tests__/results-list.tests.js, src/components/molecules/results-list/results-list-item/__tests__/results-list-item.test.js, src/components/molecules/results-list/results-list-item/results-list-item.jsx, src/components/molecules/results-list/results-list.jsx, src/views/Manual/Manual.jsx
- added tracking on the link
- added integration test
- updated unit test
Closes #60
=> (#60) added click event on result item

src/views/Manual/Manual.jsx, src/views/Manual/Manual.scss
- removed hr tag
- updated Manual.css
Closes #75
=> (#75) Fixed pager's horizontal ruler on Manual view

cypress/integration/DiseaseOnly/DiseasePrettyURLName.feature, cypress/integration/Intervention/InterventionPrettyURLName.feature, src/views/Disease/Disease.jsx, src/views/Intervention/Intervention.jsx, support/mock-data/clinical-trials/breast-cancer-25-50-request.json, support/mock-data/clinical-trials/trastuzumab-25-50-request.json
Closes #73
Closes #81 
* Remove useParams hook and set const using data instead in Disease
* Update Intervention variable name (was Disease before...)
=> (#73) Remove useParams hook from Disease

src/views/Manual/Manual.jsx, src/views/Manual/__tests__/Manual.test.js
Closes #86
* added useEffect in manual component
* aded scroll function in pagination handler
* added unit test
=> (#86) Fix scroll position on Manual

src/styles/app.scss, src/views/Disease/Disease.jsx, src/views/Disease/Disease.scss, src/views/Intervention/Intervention.jsx, src/views/Intervention/Intervention.scss
- removed hr tags
- updated condition to display pager
- added disease and intervention scss
Closes #71
=> (#71) Fix horizontal ruler

src/App.js
=> (#95) Added empty page options container

src/utils/__tests__/getLocationInfoFromSites.test.js, src/utils/getLocationInfoFromSites.js
Closes #91
* Update locations text to be lowercased instead of title cased
* Update unit test
=> (#91) Update locations casing in trial display

cypress/integration/AppAnalytics/DiseaseOnly/DiseaseAnalytics.feature, cypress/integration/common/index.js
* added click event test to DiseaseAnalytics.feature
Closes #64
=> (#64) Update analytics for Disease

src/views/Disease/Disease.jsx, src/views/Intervention/Intervention.jsx
Closes #103
*edited Invervetion.jsx and Disease.jsx redirect conditional to use payload.trials.length
=> (#103) No Trial page with CIS Banner when on-existent page number is appended to URL

src/views/Disease/Disease.jsx, src/views/Intervention/Intervention.jsx, src/views/Manual/Manual.jsx
Closes #116
* Added useEffect to set 'page' for 'pn' url parameter change when 'pn' doesn't match value in pager object
=> (#116) Browser Back Button When Paging Through Results

cypress/integration/AppAnalytics/DiseaseOnly/DiseaseAnalytics.feature, cypress/integration/AppAnalytics/Intervention/InterventionAnalytics.feature, cypress/integration/AppAnalytics/Manual/AdultMetastaticBrainTumorAnalytics.feature, cypress/integration/common/index.js, src/views/CTLViewsHoC.jsx, src/views/Disease/Disease.jsx, src/views/Intervention/Intervention.jsx
=> (#107) Add page options container to Disease and Intervention component

src/views/Disease/Disease.jsx, src/views/ErrorBoundary/ErrorPage.jsx, src/views/ErrorBoundary/PageNotFound.jsx, src/views/Intervention/Intervention.jsx, src/views/Manual/Manual.jsx, src/views/NoTrialsFound/NoTrialsFound.jsx
=> (#139) Updated name param in event tracking

package-lock.json, package.json
Closes #129
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-142/breast-cancer?cfg=0
=> (#129) NPM Audit Fix

cypress/integration/common/beforeEach.js, public/index.html, src/index.js, src/services/api/clinical-trials-search-api/__tests__/getClinicalTrials.test.js, src/services/api/clinical-trials-search-api/getClinicalTrials.js
- updated src/index.js
- updated index.html
- updated clincal-trials-search-api/getClinicalTrials.js
- updated unit and integration tests accordingly
Closes #149
=> (#149) getClinicalTrials request should not contain a hardcoded version

src/components/molecules/pager/pager.jsx
* Simplifies the logic for the pager component
* Uses absolute value to calculated distance instead of max/min combination
* Renames variables for clarity
* Restructures ellipsis logic for clarity
Closes #147
=> (#147) Simplify Pager Logic

package-lock.json, package.json
Closes: #155 
Steps:
1. `nvm use v12`
2. Update `.pa11yci`
```
"chromeLaunchConfig": {
"args": [
"--no-sandbox",
"--disable-setuid-sandbox",
"--disable-dev-shm-usage"
]
}
```
3. Run `npm install --save-dev pa11y-ci@^3.0.1`
=> (#155) Pa11y Issue Fix

package-lock.json, package.json
* `package.json` and `package-loack.json` file updates after `npm audit fix`
Closes #161
=> (#152) Update npm security vulnerabilities

package-lock.json, package.json
(Closes #162)
- uninstalled node-sass
- installed sass
=> (#162) Change out node-sass for sass
